### ISSUE TITLE
Game ăn ram liên tục

### ISSUE THREAD

**Issue by NgNhatThanh** [littlepsyduck/PROJECT-CrateMage#31]
Các b cứ thử đến màn hình complete và không làm gì, rồi mở task manager lên xem ram nó ăn là thấy vấn đề nhé :))
T nghĩ là do đoạn này ở LevelCompletedScreen, tạo Texture mới liên tục mỗi lần render 

`Texture background = new Texture("levelPass/backgrendgame.png");`

**Comment by littlepsyduck** [comment]
> Các b cứ thử đến màn hình complete và không làm gì, rồi mở task manager lên xem ram nó ăn là thấy vấn đề nhé :)) T nghĩ là do đoạn này ở LevelCompletedScreen, tạo Texture mới liên tục mỗi lần render
> 
> `Texture background = new Texture("levelPass/backgrendgame.png");`

Nhóm mình sẽ xem lại 🥲 Cảm ơn Thành nhiều he 💯
